replicaCount: 1
statefulset:
  enabled: true
#  affinityTemplate: |
#    podAntiAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: "app.kubernetes.io/name"
#                operator: In
#                values:
#                  - "{{ .Values.releaseIdentifier }}"
#          topologyKey: "kubernetes.io/hostname"
tolerations:
  - key: "uw.edu/dedicated"
    operator: "Equal"
    value: "mmcore"
    effect: "NoSchedule"
deployment:
  enabled: false
containerPorts:
  enabled: true
  ports:
    - name: http
      containerPort: 8000
      protocol: TCP
    - name: lmtp
      containerPort: 8024
      protocol: TCP
    - name: smtp
      containerPort: 25
      protocol: TCP
autoscaling:
  enabled: false
services:
  LoadBalancer:
    ports:
      - port: 25
        targetPort: 25
        protocol: TCP
        name: smtp
securityPolicy:
  enabled: false
readiness:
  enabled: true
database:
  engine: postgres
  name: mailman
  hostname: mailman-core-db-prod-service
  secretName: mailman-core-prod.axdd.s.uw.edu-sql-secret
externalService:
  enabled: true
  name: mailman-core-db-prod-service
  type: ClusterIP
  serviceAddress: 172.18.1.44
  servicePort: 5432
repo: mailman-core
instance: prod
resources:
  limits:
    cpu: 1500m
    memory: 2.5Gi
  requests:
    cpu: 500m
    memory: 1Gi
image:
  repository: REPO_PATH
  tag: IMAGE_TAG
gcsCredentials:
  mounted: true
  secretName: mailman-core-prod.axdd.s.uw.edu-gcs-credentials
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
  pushgateway:
    enabled: true
    replicaCount: 1
cronjob:
  enabled: true
certs:
  mounted: true
  certPath: /certs/mailman-core-prod.axdd.s.uw.edu.cert
  keyPath: /certs/mailman-core-prod.axdd.s.uw.edu.key
  secretName: mailman-core-prod.axdd.s.uw.edu-certs
environmentVariables:
  - name: ENV
    value: prod
externalSecrets:
  enabled: true
  secrets:
    - name: mailman-core-prod.axdd.s.uw.edu-shared-secrets
      externalKey: axdd/kv/data/mailman/shared/prod/secrets
      data:
        - name: mailman-admin-user
          property: mailman-admin-user
        - name: mailman-admin-password
          property: mailman-admin-password
        - name: hyperkitty-api-key
          property: hyperkitty-api-key
    - name: mailman-core-prod.axdd.s.uw.edu-secrets
      externalKey: axdd/kv/data/mailman/core/prod/secrets
      data:
        - name: mailman-site-owner
          property: mailman-site-owner
        - name: smtp-host
          property: smtp-host
    - name: mailman-core-prod.axdd.s.uw.edu-sql-secret
      externalKey: axdd/kv/data/mailman/core/prod/sql-secret
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: mailman-core-prod.axdd.s.uw.edu-gcs-credentials
      externalKey: axdd/kv/data/mailman/core/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: mailman-core-prod.axdd.s.uw.edu-certs
      externalKey: axdd/kv/data/mailman/core/prod/ic-certs
      data:
        - name: mailman-core-prod.axdd.s.uw.edu.key
          property: key
        - name: mailman-core-prod.axdd.s.uw.edu.cert
          property: cert
environmentVariablesSecrets:
  mailmanAdminUser:
    name: MAILMAN_ADMIN_USER
    secretName: mailman-core-prod.axdd.s.uw.edu-shared-secrets
    secretKey: mailman-admin-user
  mailmanAdminPassword:
    name: MAILMAN_ADMIN_PASSWORD
    secretName: mailman-core-prod.axdd.s.uw.edu-shared-secrets
    secretKey: mailman-admin-password
  hyperkittyAPIKey:
    name: HYPERKITTY_API_KEY
    secretName: mailman-core-prod.axdd.s.uw.edu-shared-secrets
    secretKey: hyperkitty-api-key
  mailmanSiteOwner:
    name: MAILMAN_SITE_OWNER
    secretName: mailman-core-prod.axdd.s.uw.edu-secrets
    secretKey: mailman-site-owner
  smtpHostname:
    name: SMTP_HOST
    secretName: mailman-core-prod.axdd.s.uw.edu-secrets
    secretKey: smtp-host

sidecarContainers:
  postfix:
    image: "us-docker.pkg.dev/uwit-mci-axdd/containers/uw-postfix:ca80684"
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 256Mi
  hyperkitty-cron:
    image: "us-docker.pkg.dev/uwit-mci-axdd/containers/mailman-web:70c6fd9"
    command:
      - /scripts/hyperkitty_jobs.sh
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 256Mi
    environmentVariables:
      - name: ENV
        value: prod
      - name: DB
        value: postgres
      - name: DATABASE_USERNAME
        valueFrom:
          secretKeyRef:
            name: lists.uw.edu-sql-secret
            key: username
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: lists.uw.edu-sql-secret
            key: password
      - name: DATABASE_DB_NAME
        value: mailmanweb
      - name: DATABASE_HOSTNAME
        value: mailman-web-db-prod-service
      - name: MAILMAN_REST_URL
        value: http://mailman-core-prod-prod
      - name: MAILMAN_ARCHIVER_FROM
        value: mailman-core-prod-prod
      - name: DJANGO_SECRET
        valueFrom:
          secretKeyRef:
            name: lists.uw.edu-secrets
            key: django-secret
      - name: HYPERKITTY_API_KEY
        valueFrom:
          secretKeyRef:
            name: lists.uw.edu-shared-secrets
            key: hyperkitty-api-key
  mailman-backup:
    image: "us-docker.pkg.dev/uwit-mci-axdd/containers/uw-gcp-task:7eb0a58"
    args: [ "/scripts/cron.sh", "/config/backup.cron"]
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 64Mi
    environmentVariables:
      - name: GCLOUD_AUTH_FILE
        value: /gcs/credentials.json

podVolumes:
  var-mailman:
    volume:
      claimTemplate:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        storageSize: 100Gi
    mount:
      mountPath: /app/mailman/var
    containers: [ base, postfix, hyperkitty-cron, mailman-backup ]
  var-spool-postfix:
    volume:
      claimTemplate:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        storageSize: 10Gi
    mount:
      mountPath: /var/spool/postfix
    containers: [ base, postfix ]
  postfix-config:
    volume:
      configMap:
        name: postfix-main-tpl
    mount:
      mountPath: /config/main.tpl
      subPath: main.tpl
    containers: [ postfix ]
  postfix-master-config:
    volume:
      configMap:
        name: postfix-master-tpl
    mount:
      mountPath: /config/master.tpl
      subPath: master.tpl
    containers: [ postfix ]
  mailman-config-template:
    volume:
      configMap:
        name: mailman-tpl
    mount:
      mountPath: /config/mailman.tpl
      subPath: mailman.tpl
    containers: [ base ]
  mailman-hyperkitty-config-template:
    volume:
      configMap:
        name: mailman-hyperkitty-tpl
    mount:
      mountPath: /config/mailman-hyperkitty.tpl
      subPath: mailman-hyperkitty.tpl
    containers: [ base ]
  mailman-gunicorn-config-template:
    volume:
      configMap:
        name: gunicorn-tpl
    mount:
      mountPath: /config/gunicorn.tpl
      subPath: gunicorn.tpl
    containers: [ base ]
  mailman-postfix-mailman-config-template:
    volume:
      configMap:
        name: postfix-mailman-tpl
    mount:
      mountPath: /config/postfix-mailman.tpl
      subPath: postfix-mailman.tpl
  mailman-backup-schedule:
    volume:
      configMap:
        name: mailman-backup-schedule
    mount:
      mountPath: /config/backup.cron
      subPath: backup.cron
    containers: [ mailman-backup ]
  hyperkitty-cron-schedule:
    volume:
      configMap:
        name: hyperkitty-cron-schedule
    mount:
      mountPath: /config/hyperkitty.cron
      subPath: hyperkitty.cron
    containers: [ hyperkitty-cron ]

configmaps:
  postfix-main-tpl:
    main.tpl: |
      myhostname = lists.uw.edu
      mail_name = "UW Mailman"
      mail_owner = postfix
      setgid_group = postdrop
      maillog_file = /dev/stdout
      smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
      biff = no
      queue_directory = /var/spool/postfix
      data_directory = /var/lib/postfix
      append_dot_mydomain = no
      readme_directory = no
      compatibility_level = 2
      smtpd_tls_cert_file = /certs/mailman-core-prod.axdd.s.uw.edu.cert
      smtpd_tls_key_file = /certs/mailman-core-prod.axdd.s.uw.edu.key
      smtpd_use_tls = yes
      smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
      smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
      smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination
      alias_maps = hash:/etc/aliases
      alias_database = hash:/etc/aliases
      mydestination = $myhostname, $mydomain, localhost, localhost.localdomain
      mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
      mailbox_size_limit = 0
      recipient_delimiter = +
      unknown_local_recipient_reject_code = 550
      owner_request_special = no
      inet_interfaces = all
      inet_protocols = ipv4
      transport_maps = regexp:/app/mailman/var/data/postfix_lmtp
      local_recipient_maps = regexp:/app/mailman/var/data/postfix_lmtp
      relay_domains = regexp:/app/mailman/var/data/postfix_domains
      virtual_alias_maps = regexp:/app/mailman/var/data/postfix_vmap
      smtp_host_lookup = native,dns
      lmtp_host_lookup = native,dns
  postfix-master-tpl:
    master.tpl: |
      # Postfix master process configuration file.  For details on the format
      # of the file, see the master(5) manual page (command: "man 5 master" or
      # on-line: http://www.postfix.org/master.5.html).
      # ==========================================================================
      # service type  private unpriv  chroot  wakeup  maxproc command + args
      #               (yes)   (yes)   (no)    (never) (100)
      # ==========================================================================
      smtp      inet  n       -       n       -       -       smtpd
      pickup    unix  n       -       n       60      1       pickup
      cleanup   unix  n       -       n       -       0       cleanup
      qmgr      unix  n       -       n       300     1       qmgr
      tlsmgr    unix  -       -       n       1000?   1       tlsmgr
      rewrite   unix  -       -       n       -       -       trivial-rewrite
      bounce    unix  -       -       n       -       0       bounce
      defer     unix  -       -       n       -       0       bounce
      trace     unix  -       -       n       -       0       bounce
      verify    unix  -       -       n       -       1       verify
      flush     unix  n       -       n       1000?   0       flush
      proxymap  unix  -       -       n       -       -       proxymap
      proxywrite unix -       -       n       -       1       proxymap
      smtp      unix  -       -       n       -       -       smtp
      relay     unix  -       -       n       -       -       smtp -o syslog_name=postfix/$service_name
      showq     unix  n       -       n       -       -       showq
      error     unix  -       -       n       -       -       error
      retry     unix  -       -       n       -       -       error
      discard   unix  -       -       n       -       -       discard
      local     unix  -       n       n       -       -       local
      virtual   unix  -       n       n       -       -       virtual
      lmtp      unix  -       -       n       -       -       lmtp
      anvil     unix  -       -       n       -       1       anvil
      scache    unix  -       -       n       -       1       scache
      postlog   unix-dgram n  -       n       -       1       postlogd
      # ====================================================================
      # Interfaces to non-Postfix software. Be sure to examine the manual
      # pages of the non-Postfix software to find out what options it wants.
      maildrop  unix  -       n       n       -       -       pipe flags=DRhu user=vmail argv=/usr/bin/maildrop -d ${recipient}
      uucp      unix  -       n       n       -       -       pipe flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
      ifmail    unix  -       n       n       -       -       pipe flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
      bsmtp     unix  -       n       n       -       -       pipe flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
      scalemail-backend unix	-	n	n	-	2	pipe flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
      #mailman   unix  -       n       n       -       -       pipe flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py ${nexthop} ${user}
  mailman-tpl:
    mailman.tpl: |
      [paths.master]
      var_dir: /app/mailman/var
      [database]
      ${DATABASE_URL}
      ${DATABASE_CLASS}
      [runner.retry]
      sleep_time: 10s
      [webservice]
      hostname: ${MAILMAN_HOSTNAME}
      port: 8000
      admin_user: ${MAILMAN_ADMIN_USER}
      admin_pass: ${MAILMAN_ADMIN_PASSWORD}
      configuration: /app/mailman/var/etc/gunicorn.cfg
      [archiver.hyperkitty]
      class: mailman_hyperkitty.Archiver
      enable: yes
      configuration: /app/mailman/var/etc/mailman-hyperkitty.cfg
      [mta]
      #incoming: mailman.mta.exim4.LMTP
      incoming: mailman.mta.postfix.LMTP
      outgoing: mailman.mta.deliver.deliver
      lmtp_host: ${MAILMAN_HOSTNAME}
      lmtp_port: 8024
      smtp_host: ${SMTP_HOST}
      smtp_port: 25
      #configuration: python:mailman.config.exim4
      configuration: /app/mailman/var/etc/postfix-mailman.cfg
      [mailman]
      site_owner: ${MAILMAN_SITE_OWNER}
      [logging.template]
      path: /dev/stdout
      [logging.archiver]
      path: /dev/stdout
      [logging.config]
      path: /dev/stdout
      [logging.subscribe]
      path: /dev/stdout
      [logging.mischief]
      path: /dev/stdout
      [logging.database]
      path: /dev/stdout
      [logging.http]
      path: /dev/stdout
      [logging.error]
      path: /dev/stdout
      [logging.root]
      path: /dev/stdout
      level: debug
      [logging.bounce]
      path: /dev/stdout
      [logging.debug]
      path: /dev/stdout
      [logging.plugins]
      path: /dev/stdout
      [logging.smtp]
      path: /dev/stdout
      [logging.runner]
      path: /dev/stdout
  mailman-hyperkitty-tpl:
    mailman-hyperkitty.tpl: |
      [general]
      base_url: http://mailman-web-prod-prod/hyperkitty/
      api_key: ${HYPERKITTY_API_KEY}
  gunicorn-tpl:
    gunicorn.tpl: |
      [gunicorn]
      graceful_timeout = 30
      timeout = 360
  postfix-mailman-tpl:
    postfix-mailman.tpl: |
      [postfix]
      transport_file_type: regex
      postmap_command: true
  mailman-backup-schedule:
    backup.cron: |
      10 1 * * * /scripts/backup.sh 0 /app/mailman/var mailman-backups
  hyperkitty-cron-schedule:
    hyperkitty.cron: |
      # This goes in /etc/cron.d/.
      # Replace "apache" by your webserver user ("www-data" on Debian systems) and
      # set the path to the Django project directory
      @hourly   /app/scripts/hyperkitty_cron hourly
      @daily    /app/scripts/hyperkitty_cron daily
      @weekly   /app/scripts/hyperkitty_cron weekly
      @monthly  /app/scripts/hyperkitty_cron monthly
      @yearly   /app/scripts/hyperkitty_cron yearly
      # Currently Hyperkitty has no minutely and quarter_hourly jobs.  The purpose of
      # the next lines is to ease the upgrading process, in the eventual case that
      # Hyperkitty will utilize minutely or quarter_hourly jobs.
      2,17,32,47 * * * * /app/scripts/hyperkitty_cron quarter_hourly
      * * * * *  /app/scripts/hyperkitty_cron minutely
