replicaCount: 1
statefulset:
  enabled: true
deployment:
  enabled: false
containerPorts:
  enabled: true
  ports:
    - name: http
      containerPort: 8000
      protocol: TCP
    - name: smtp
      containerPort: 25
      protocol: TCP
autoscaling:
  enabled: false
ingress:
  enabled: true
  type: nginx
  tls:
    test-mailman-core:
      secretName: mailman-core-test.axdd.s.uw.edu-ingress-cert
      hosts:
        - mailman-core-test.axdd.s.uw.edu
  hosts:
    test-mailman-core:
      host: mailman-core-test.axdd.s.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
securityPolicy:
  enabled: false
readiness:
  enabled: true
database:
  engine: postgres
  name: mailman
  hostname: mailman-core-db-test-service
  secretName: mailman-core-test.axdd.s.uw.edu-sql-secret
externalService:
  enabled: true
  name: mailman-core-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.1.64
  servicePort: 5432
repo: mailman-core
instance: test
resources:
  limits:
    cpu: 550m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi
persistentVolume:
  enabled: true
  claimTemplates:
    - name: var-mailman
      accessModes:
        - ReadWriteOnce
      mountPath: /app/mailman/var
      storageClassName: standard
      storageSize: 10Gi
    - name: var-spool-postfix
      accessModes:
        - ReadWriteOnce
      mountPath: /var/spool/postfix
      storageClassName: standard
      storageSize: 3Gi
image:
  repository: gcr.io/uwit-mci-axdd/mailman-core
  tag: IMAGE_TAG
metrics:
  enabled: false
memcached:
  enabled: false
certs:
  mounted: false
environmentVariables:
  - name: ENV
    value: dev
externalSecrets:
  enabled: true
  secrets:
    - name: mailman-core-test.axdd.s.uw.edu-shared-secrets
      externalKey: axdd/kv/data/mailman/shared/test/secrets
      data:
        - name: mailman-admin-user
          property: mailman-admin-user
        - name: mailman-admin-password
          property: mailman-admin-password
        - name: hyperkitty-api-key
          property: hyperkitty-api-key
    - name: mailman-core-test.axdd.s.uw.edu-secrets
      externalKey: axdd/kv/data/mailman/core/test/secrets
      data:
        - name: mailman-site-owner
          property: mailman-site-owner
        - name: smtp-host
          property: smtp-host
    - name: mailman-core-test.axdd.s.uw.edu-sql-secret
      externalKey: axdd/kv/data/mailman/core/test/sql-secret
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: postfix-test-secrets
      externalKey: axdd/kv/data/postfix/test/secrets
      data:
        - name: jumphost-id-key
          property: jumphost-id-key
        - name: jumphost-id
          property: jumphost-id
        - name: jumphost-hostname
          property: jumphost-hostname
        - name: smtp-server
          property: smtp-server
environmentVariablesSecrets:
  mailmanAdminUser:
    name: MAILMAN_ADMIN_USER
    secretName: mailman-core-test.axdd.s.uw.edu-shared-secrets
    secretKey: mailman-admin-user
  mailmanAdminPassword:
    name: MAILMAN_ADMIN_PASSWORD
    secretName: mailman-core-test.axdd.s.uw.edu-shared-secrets
    secretKey: mailman-admin-password
  hyperkittyAPIKey:
    name: HYPERKITTY_API_KEY
    secretName: mailman-core-test.axdd.s.uw.edu-shared-secrets
    secretKey: hyperkitty-api-key
  mailmanSiteOwner:
    name: MAILMAN_SITE_OWNER
    secretName: mailman-core-test.axdd.s.uw.edu-secrets
    secretKey: mailman-site-owner
  smtpHostname:
    name: SMTP_HOST
    secretName: mailman-core-test.axdd.s.uw.edu-secrets
    secretKey: smtp-host

sidecarContainers:
  postfix:
    image: "gcr.io/uwit-mci-axdd/uw-postfix:590c196"
    volumeMounts:
      - mountPath: /var/spool/postfix
        name: mailman-core-prod-test-pvc-var-spool-postfix
      - mountPath: /app/mailman/var
        name: mailman-core-prod-test-pvc-var-mailman
      - mountPath: /config/main.cf
        subPath: main.cf
        name: postfix-config
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 256Mi
  smtpforward:
    image: kroniak/ssh-client
    env:
      - name: JUMPHOST_ID_KEY
        valueFrom:
          secretKeyRef:
            name: postfix-test-secrets
            key: jumphost-id-key
      - name: JUMPHOST_ID
        valueFrom:
          secretKeyRef:
            name: postfix-test-secrets
            key: jumphost-id
      - name: JUMPHOST_HOSTNAME
        valueFrom:
          secretKeyRef:
            name: postfix-test-secrets
            key: jumphost-hostname
      - name: SMTP_SERVER
        valueFrom:
          secretKeyRef:
            name: postfix-test-secrets
            key: smtp-server
    command:
      - "sh"
      - "-c"
      - 'mkdir -m 0700 ~/.ssh && echo "${JUMPHOST_ID_KEY}" > ~/.ssh/id_ecdsa && chmod 400 ~/.ssh/id_ecdsa && ssh ${JUMPHOST_ID}@${JUMPHOST_HOSTNAME} -o StrictHostKeyChecking=no -N -L 127.0.0.1:25:{SMTP_SERVER}:25'

podVolumes:
  postfix-config:
    configMap:
      name: mailman-core-prod-test-configmap-postfix-main-cf
  mailmain-config-template:
    configMap:
      name: mailman-core-prod-test-configmap-mailman-tpl
  mailmain-hyperkitty-config-template:
    configMap:
      name: mailman-core-prod-test-configmap-mailman-hyperkitty-tpl
  mailmain-gunicorn-config-template:
    configMap:
      name: mailman-core-prod-test-configmap-gunicorn-tpl
  mailmain-postfix-mailman-config-template:
    configMap:
      name: mailman-core-prod-test-configmap-postfix-mailman-tpl

volumeMounts:
  - name: mailmain-config-template
    mountPath: /config/mailman.tpl
    subPath: mailman.tpl
  - name: mailmain-hyperkitty-config-template
    mountPath: /config/mailman-hyperkitty.tpl
    subPath: mailman-hyperkitty.tpl
  - name: mailmain-gunicorn-config-template
    mountPath: /config/gunicorn.tpl
    subPath: gunicorn.tpl
  - name: mailmain-postfix-mailman-config-template
    mountPath: /config/postfix-mailman.tpl
    subPath: postfix-mailman.tpl

configmaps:
  postfix-main-cf:
    main.cf: |
      myhostname = mailman-core-prod-test
      mail_name = Mailman POC
      relayhost = smtp.uw.edu
      mail_owner = postfix
      setgid_group = postdrop
      maillog_file = /dev/stdout
      smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
      biff = no
      queue_directory = /var/spool/postfix
      data_directory = /var/lib/postfix
      append_dot_mydomain = no
      readme_directory = no
      compatibility_level = 2
      smtpd_tls_cert_file = /certs/ssl-cert-snakeoil.pem
      smtpd_tls_key_file = /certs/ssl-cert-snakeoil.key
      smtpd_use_tls = yes
      smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
      smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
      smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
      alias_maps = hash:/etc/aliases
      alias_database = hash:/etc/aliases
      mydestination = $myhostname, /etc/mailname, localhost, localhost.localdomain, localhost
      mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
      mailbox_size_limit = 0
      recipient_delimiter = +
      inet_interfaces = all
      inet_protocols = ipv4
  mailman-tpl:
    mailman.tpl: |
      [paths.master]
      var_dir: /app/mailman/var
      [database]
      ${DATABASE_URL}
      ${DATABASE_CLASS}
      [runner.retry]
      sleep_time: 10s
      [webservice]
      hostname: ${MAILMAN_HOSTNAME}
      port: 8000
      admin_user: ${MAILMAN_ADMIN_USER}
      admin_pass: ${MAILMAN_ADMIN_PASSWORD}
      configuration: /app/mailman/var/etc/gunicorn.cfg
      [archiver.hyperkitty]
      class: mailman_hyperkitty.Archiver
      enable: yes
      configuration: /app/mailman/var/etc/mailman-hyperkitty.cfg
      [mta]
      #incoming: mailman.mta.exim4.LMTP
      incoming: mailman.mta.postfix.LMTP
      outgoing: mailman.mta.deliver.deliver
      lmtp_host: ${MAILMAN_HOSTNAME}
      lmtp_port: 8024
      smtp_host: ${SMTP_HOST}
      smtp_port: 25
      #configuration: python:mailman.config.exim4
      configuration: /app/mailman/var/etc/postfix-mailman.cfg
      [mailman]
      site_owner: ${MAILMAN_SITE_OWNER}
      [logging.root]
      path: /dev/stdout
  mailman-hyperkitty-tpl:
    mailman-hyperkitty.tpl: |
      [general]
      base_url: ${HYPERKITTY_BASE_URL}/hyperkitty/
      api_key: ${HYPERKITTY_API_KEY}
  gunicorn-tpl:
    gunicorn.tpl: |
      [gunicorn]
      graceful_timeout = 30
      timeout = 360
  postfix-mailman-tpl:
    postfix-mailman.tpl: |
      [postfix]
      transport_file_type: regex
      postmap_command: true
